config/routes.rb
Tareas::Application.routes.draw do
  resources :responsables

  resources :tareas

end

app/models/responsable.rb
class Responsable < ActiveRecord::Base
  attr_accessible :nombre, :email
  has_many :tareas
end

app/models/tarea.rb
class Tarea < ActiveRecord::Base
  attr_accessible :nombre, :detalles, :fecha ,:responsable_id
  validates :nombre, presence: true
  belongs_to :responsable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/responsables_controller.rb
class ResponsablesController < ApplicationController
  # GET /responsables
  # GET /responsables.json
  def index
    @responsables = Responsable.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @responsables }
    end
  end

  # GET /responsables/1
  # GET /responsables/1.json
  def show
    @responsable = Responsable.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @responsable }
    end
  end

  # GET /responsables/new
  # GET /responsables/new.json
  def new
    @responsable = Responsable.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @responsable }
    end
  end

  # GET /responsables/1/edit
  def edit
    @responsable = Responsable.find(params[:id])
  end

  # POST /responsables
  # POST /responsables.json
  def create
    @responsable = Responsable.new(params[:responsable])

    respond_to do |format|
      if @responsable.save
        format.html { redirect_to @responsable, notice: 'Responsable was successfully created.' }
        format.json { render json: @responsable, status: :created, location: @responsable }
      else
        format.html { render action: "new" }
        format.json { render json: @responsable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /responsables/1
  # PUT /responsables/1.json
  def update
    @responsable = Responsable.find(params[:id])

    respond_to do |format|
      if @responsable.update_attributes(params[:responsable])
        format.html { redirect_to @responsable, notice: 'Responsable was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @responsable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responsables/1
  # DELETE /responsables/1.json
  def destroy
    @responsable = Responsable.find(params[:id])
    @responsable.destroy

    respond_to do |format|
      format.html { redirect_to responsables_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tareas_controller.rb
class TareasController < ApplicationController
  # GET /tareas
  # GET /tareas.json
  def index
    @tareas = Tarea.paginate(:page => params[:page], :per_page => 2).order('fecha')


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tareas }
    end
  end

  # GET /tareas/1
  # GET /tareas/1.json
  def show
    @tarea = Tarea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tarea }
    end
  end

  # GET /tareas/new
  # GET /tareas/new.json
  def new
    @tarea = Tarea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tarea }
    end
  end

  # GET /tareas/1/edit
  def edit
    @tarea = Tarea.find(params[:id])
  end

  # POST /tareas
  # POST /tareas.json
  def create
    @tarea = Tarea.new(params[:tarea])

    respond_to do |format|
      if @tarea.save
        format.html { redirect_to @tarea, notice: 'Tarea was successfully created.' }
        format.json { render json: @tarea, status: :created, location: @tarea }
      else
        format.html { render action: "new" }
        format.json { render json: @tarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tareas/1
  # PUT /tareas/1.json
  def update
    @tarea = Tarea.find(params[:id])

    respond_to do |format|
      if @tarea.update_attributes(params[:tarea])
        format.html { redirect_to @tarea, notice: 'Tarea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tareas/1
  # DELETE /tareas/1.json
  def destroy
    @tarea = Tarea.find(params[:id])
    @tarea.destroy

    respond_to do |format|
      format.html { redirect_to tareas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/responsables_helper.rb
module ResponsablesHelper
end

app/helpers/tareas_helper.rb
module TareasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tareas</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/responsables/_form.html.erb
<%= form_for(@responsable) do |f| %>
  <% if @responsable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@responsable.errors.count, "error") %> prohibited this responsable from being saved:</h2>

      <ul>
      <% @responsable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/responsables/edit.html.erb
<h1>Editing responsable</h1>

<%= render 'form' %>

<%= link_to 'Show', @responsable %> |
<%= link_to 'Back', responsables_path %>

app/views/responsables/index.html.erb
<h1>Listado de Responsables</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @responsables.each do |responsable| %>
  <tr>
    <td><%= responsable.nombre %></td>
    <td><%= responsable.email %></td>
    <td><%= link_to 'Show', responsable %></td>
    <td><%= link_to 'Edit', edit_responsable_path(responsable) %></td>
    <td><%= link_to 'Destroy', responsable, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Responsable', new_responsable_path %>

app/views/responsables/new.html.erb
<h1>New responsable</h1>

<%= render 'form' %>

<%= link_to 'Back', responsables_path %>

app/views/responsables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @responsable.nombre %>
  <b>Email:</b>
  <%= @responsable.email %>
</p>


<%= link_to 'Edit', edit_responsable_path(@responsable) %> |
<%= link_to 'Back', responsables_path %>

app/views/tareas/_form.html.erb
<%= form_for(@tarea) do |f| %>
  <% if @tarea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tarea.errors.count, "error") %> prohibited this tarea from being saved:</h2>

      <ul>
      <% @tarea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
   <%= f.label :detalles %><br />
   <%= f.text_area :detalles, rows: 5 %>
 </div>
  <div class="field">
   <%= f.label :responsable_id %><br />
   <%= f.select(:responsable_id, Responsable.all.map{|a|[a.nombre, a.id]}) %>
 </div>
  <div class="field">
   <%= f.label :fecha %><br />
   <%= f.date_select :fecha %>
 </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tareas/edit.html.erb
<h1>Editing tarea</h1>

<%= render 'form' %>

<%= link_to 'Show', @tarea %> |
<%= link_to 'Back', tareas_path %>

app/views/tareas/index.html.erb
<h1>Listing tareas</h1>

<table>
  <tr>
    <th>NombrEE</th>
    <th>Detalles</th>
    <th>Fecha</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tareas.each do |tarea| %>
  <tr>
    <td><%= tarea.nombre %></td> 
    <td><%= truncate tarea.detalles, length: 25 %></td>
    <td><%= tarea.fecha %></td>
    <td><%= link_to 'Show', tarea %></td>
    <td><%= link_to 'Edit', edit_tarea_path(tarea) %></td>
    <td><%= link_to 'Destroy', tarea, confirm: 'Are you sure?', method: :delete %></td>
   </tr>
<% end %>
</table>

<br />

<%= will_paginate @tareas %>
<%= link_to 'New Tarea', new_tarea_path %>

app/views/tareas/new.html.erb
<h1>New tarea</h1>

<%= render 'form' %>

<%= link_to 'Back', tareas_path %>

app/views/tareas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @tarea.nombre %>
</p>
<p>
  <b>Detalles:</b>
  <%= @tarea.detalles %>
</p>
<p>
  <b>Fecha:</b>
  <%= @tarea.fecha %>
</p>

<%= link_to 'Edit', edit_tarea_path(@tarea) %> |
<%= link_to 'Back', tareas_path %>